version: '3.8'

services:
  api-gateway:
    build: ./MicroServicesBackend/api-gateway
    image: nlawej-api-gateway
    container_name: api-gateway
    ports:
      - "8081:8081"
    depends_on:
      - consul
    environment:
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
    networks:
      - nlawej-network

  consul:
    image: consul:1.15.4
    container_name: consul
    ports:
      - "8500:8500"
    networks:
      - nlawej-network

  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: Nlawej
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - nlawej-network


  # Authentication service instances
  authentication-service:
    build: ./MicroServicesBackend/authentication-service
    image: nlawej-authentication
    container_name: authentication-service
    ports:
      - "3000:3000"
    volumes:
      - ./MicroServicesBackend/authentication-service:/app
      - /app/node_modules
    environment:
      - HTTPS=true
      - NODE_ENV=development
      - MONGO_URI=mongodb://root:example@mongodb:27017/Nlawej?authSource=admin
      - HOST=authentication-service
      - SESSION_SECRET=${SESSION_SECRET}
      - GOOGLE_CLIENT_ID=${CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${CLIENT_SECRET}
      - SERVICE_NAME=authentication-service       # <-- ajouté
      - SERVICE_ID=authentication-service-0
      - CONSUL_HOST=consul
    depends_on:
      mongodb:
        condition: service_healthy
      consul:
        condition: service_started
    restart: always
    networks:
      - nlawej-network


  authentication-1:
    build: ./MicroServicesBackend/authentication-service
    image: nlawej-authentication
    container_name: authentication-1
    ports:
      - "3001:3000"
    environment:
      - SERVICE_NAME=authentication-service
      - SERVICE_ID=authentication-service-1
      - CONSUL_HOST=consul
      - MONGO_URI=mongodb://root:example@mongodb:27017/Nlawej?authSource=admin
      - HOST=authentication-1
    depends_on:
      - consul
      - mongodb
    restart: always
    networks:
      - nlawej-network


  authentication-2:
    build: ./MicroServicesBackend/authentication-service
    image: nlawej-authentication
    container_name: authentication-2
    ports:
      - "3002:3000"
    environment:
      - SERVICE_NAME=authentication-service
      - SERVICE_ID=authentication-service-2
      - CONSUL_HOST=consul
      - MONGO_URI=mongodb://root:example@mongodb:27017/Nlawej?authSource=admin
      - HOST=authentication-2
    depends_on:
      - consul
      - mongodb
    restart: always
    networks:
      - nlawej-network

  project-service:
    build: ./MicroServicesBackend/project-service
    image: nlawej-project-service
    container_name: project-service
    ports:
      - "4000:4000"
    volumes:
      - ./MicroServicesBackend/project-service:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://root:example@mongodb:27017/Nlawej?authSource=admin
      - HOST=project-service
      - SESSION_SECRET=${SESSION_SECRET}
      - SERVICE_NAME=project-service          # <-- ajouté
      - SERVICE_ID=project-service-0          # <- ID unique
      - CONSUL_HOST=consul
    depends_on:
      mongodb:
        condition: service_healthy
      consul:
        condition: service_started
    restart: always
    networks:
      - nlawej-network

  project-service-1:
    build: ./MicroServicesBackend/project-service
    image: nlawej-project-service
    container_name: project-service-1
    ports:
      - "4001:4000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://root:example@mongodb:27017/Nlawej?authSource=admin
      - HOST=project-service-1
      - SERVICE_NAME=project-service
      - SERVICE_ID=project-service-1
      - CONSUL_HOST=consul
    depends_on:
      - consul
      - mongodb
    restart: always
    networks:
      - nlawej-network

  project-service-2:
    build: ./MicroServicesBackend/project-service
    image: nlawej-project-service
    container_name: project-service-2
    ports:
      - "4002:4000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://root:example@mongodb:27017/Nlawej?authSource=admin
      - HOST=project-service-2
      - SERVICE_NAME=project-service
      - SERVICE_ID=project-service-2
      - CONSUL_HOST=consul
    depends_on:
      - consul
      - mongodb
    restart: always
    networks:
      - nlawej-network

  # Blogs promotions service instances
  blogs-promotions-service:
    build: ./MicroServicesBackend/blogs-promotions-service
    image: nlawej-blogs-promotions
    container_name: blogs-promotions-service
    ports:
      - "5067:5067"
    environment:
      - NODE_ENV=development
      - SERVICE_NAME=blogs-promotions-service
      - SERVICE_ID=blogs-promotions-service-0
      - CONSUL_HOST=consul
      - HOST=blogs-promotions-service
      - MONGO_URI=mongodb://root:example@mongodb:27017/Nlawej?authSource=admin
    depends_on:
      - consul
    restart: always
    networks:
      - nlawej-network

  blogs-promotions-service-1:
    build: ./MicroServicesBackend/blogs-promotions-service
    image: nlawej-blogs-promotions
    container_name: blogs-promotions-service-1
    ports:
      - "5062:5067"
    environment:
      - NODE_ENV=development
      - SERVICE_NAME=blogs-promotions-service
      - SERVICE_ID=blogs-promotions-service-1
      - CONSUL_HOST=consul
      - HOST=blogs-promotions-service-1
      - MONGO_URI=mongodb://root:example@mongodb:27017/Nlawej?authSource=admin
    depends_on:
      - consul
    restart: always
    networks:
      - nlawej-network

  blogs-promotions-service-2:
    build: ./MicroServicesBackend/blogs-promotions-service
    image: nlawej-blogs-promotions
    container_name: blogs-promotions-service-2
    ports:
      - "5073:5067"
    environment:
      - NODE_ENV=development
      - SERVICE_NAME=blogs-promotions-service
      - SERVICE_ID=blogs-promotions-service-2
      - CONSUL_HOST=consul
      - HOST=blogs-promotions-service-2
      - MONGO_URI=mongodb://root:example@mongodb:27017/Nlawej?authSource=admin
    depends_on:
      - consul
    restart: always
    networks:
      - nlawej-network

  # Geo service instances
  geo-service:
    build: ./MicroServicesBackend/geo-service
    image: nlawej-geo
    container_name: geo-service
    ports:
      - "3078:3078"
    environment:
      - NODE_ENV=development
      - SERVICE_NAME=geo-service
      - SERVICE_ID=geo-service-0
      - CONSUL_HOST=consul
      - HOST=geo-service
      - MONGO_URI=mongodb://root:example@mongodb:27017/Nlawej?authSource=admin
    depends_on:
      - consul
    restart: always
    networks:
      - nlawej-network

  geo-service-1:
    build: ./MicroServicesBackend/geo-service
    image: nlawej-geo
    container_name: geo-service-1
    ports:
      - "3079:3078"
    environment:
      - NODE_ENV=development
      - SERVICE_NAME=geo-service
      - SERVICE_ID=geo-service-1
      - CONSUL_HOST=consul
      - HOST=geo-service-1
      - MONGO_URI=mongodb://root:example@mongodb:27017/Nlawej?authSource=admin
    depends_on:
      - consul
    restart: always
    networks:
      - nlawej-network

  geo-service-2:
    build: ./MicroServicesBackend/geo-service
    image: nlawej-geo
    container_name: geo-service-2
    ports:
      - "3080:3078"
    environment:
      - NODE_ENV=development
      - SERVICE_NAME=geo-service
      - SERVICE_ID=geo-service-2
      - CONSUL_HOST=consul
      - HOST=geo-service-2
      - MONGO_URI=mongodb://root:example@mongodb:27017/Nlawej?authSource=admin
    depends_on:
      - consul
    restart: always
    networks:
      - nlawej-network

  # Messaging service instances
  messaging-service:
    build: ./MicroServicesBackend/messaging-service
    image: nlawej-messaging
    container_name: messaging-service
    ports:
      - "4007:4007"
    environment:
      - NODE_ENV=development
      - SERVICE_NAME=messaging-service
      - SERVICE_ID=messaging-service-0
      - CONSUL_HOST=consul
      - HOST=messaging-service
      - MONGO_URI=mongodb://root:example@mongodb:27017/Nlawej?authSource=admin
    depends_on:
      - consul
    restart: always
    networks:
      - nlawej-network

  messaging-service-1:
    build: ./MicroServicesBackend/messaging-service
    image: nlawej-messaging
    container_name: messaging-service-1
    ports:
      - "4008:4007"
    environment:
      - NODE_ENV=development
      - SERVICE_NAME=messaging-service
      - SERVICE_ID=messaging-service-1
      - CONSUL_HOST=consul
      - HOST=messaging-service-1
      - MONGO_URI=mongodb://root:example@mongodb:27017/Nlawej?authSource=admin
    depends_on:
      - consul
    restart: always
    networks:
      - nlawej-network

  messaging-service-2:
    build: ./MicroServicesBackend/messaging-service
    image: nlawej-messaging
    container_name: messaging-service-2
    ports:
      - "4009:4007"
    environment:
      - NODE_ENV=development
      - SERVICE_NAME=messaging-service
      - SERVICE_ID=messaging-service-2
      - CONSUL_HOST=consul
      - HOST=messaging-service-2
      - MONGO_URI=mongodb://root:example@mongodb:27017/Nlawej?authSource=admin
    depends_on:
      - consul
    restart: always
    networks:
      - nlawej-network

  # Notification service instances
  notification-service:
    build: ./MicroServicesBackend/notification-service
    image: nlawej-notification
    container_name: notification-service
    ports:
      - "5002:5002"
    environment:
      - NODE_ENV=development
      - SERVICE_NAME=notification-service
      - SERVICE_ID=notification-service-0
      - CONSUL_HOST=consul
      - HOST=notification-service
      - MONGO_URI=mongodb://root:example@mongodb:27017/Nlawej?authSource=admin
    depends_on:
      - consul
    restart: always
    networks:
      - nlawej-network

  notification-service-1:
    build: ./MicroServicesBackend/notification-service
    image: nlawej-notification
    container_name: notification-service-1
    ports:
      - "5003:5002"
    environment:
      - NODE_ENV=development
      - SERVICE_NAME=notification-service
      - SERVICE_ID=notification-service-1
      - CONSUL_HOST=consul
      - HOST=notification-service-1
      - MONGO_URI=mongodb://root:example@mongodb:27017/Nlawej?authSource=admin
    depends_on:
      - consul
    restart: always
    networks:
      - nlawej-network

  notification-service-2:
    build: ./MicroServicesBackend/notification-service
    image: nlawej-notification
    container_name: notification-service-2
    ports:
      - "5004:5002"
    environment:
      - NODE_ENV=development
      - SERVICE_NAME=notification-service
      - SERVICE_ID=notification-service-2
      - CONSUL_HOST=consul
      - HOST=notification-service-2
      - MONGO_URI=mongodb://root:example@mongodb:27017/Nlawej?authSource=admin
    depends_on:
      - consul
    restart: always
    networks:
      - nlawej-network

  # Offres promotions service instances
  offres-promotions-service:
    build: ./MicroServicesBackend/offres-promotions-service
    image: nlawej-offres-promotions
    container_name: offres-promotions-service
    ports:
      - "5068:5068"
    environment:
      - NODE_ENV=development
      - SERVICE_NAME=offres-promotions-service
      - SERVICE_ID=offres-promotions-service-0
      - CONSUL_HOST=consul
      - HOST=offres-promotions-service
      - MONGO_URI=mongodb://root:example@mongodb:27017/Nlawej?authSource=admin
    depends_on:
      - consul
    restart: always
    networks:
      - nlawej-network

  offres-promotions-service-1:
    build: ./MicroServicesBackend/offres-promotions-service
    image: nlawej-offres-promotions
    container_name: offres-promotions-service-1
    ports:
      - "5069:5068"
    environment:
      - NODE_ENV=development
      - SERVICE_NAME=offres-promotions-service
      - SERVICE_ID=offres-promotions-service-1
      - CONSUL_HOST=consul
      - HOST=offres-promotions-service-1
      - MONGO_URI=mongodb://root:example@mongodb:27017/Nlawej?authSource=admin
    depends_on:
      - consul
    restart: always
    networks:
      - nlawej-network

  offres-promotions-service-2:
    build: ./MicroServicesBackend/offres-promotions-service
    image: nlawej-offres-promotions
    container_name: offres-promotions-service-2
    ports:
      - "5070:5068"
    environment:
      - NODE_ENV=development
      - SERVICE_NAME=offres-promotions-service
      - SERVICE_ID=offres-promotions-service-2
      - CONSUL_HOST=consul
      - HOST=offres-promotions-service-2
      - MONGO_URI=mongodb://root:example@mongodb:27017/Nlawej?authSource=admin
    depends_on:
      - consul
    restart: always
    networks:
      - nlawej-network

  # Payment service instances
  payment-service:
    build: ./MicroServicesBackend/payment-service
    image: nlawej-payment
    container_name: payment-service
    ports:
      - "6005:6005"
    environment:
      - NODE_ENV=development
      - SERVICE_NAME=payment-service
      - SERVICE_ID=payment-service-0
      - CONSUL_HOST=consul
      - HOST=payment-service
      - MONGO_URI=mongodb://root:example@mongodb:27017/Nlawej?authSource=admin
    depends_on:
      - consul
    restart: always
    networks:
      - nlawej-network

  payment-service-1:
    build: ./MicroServicesBackend/payment-service
    image: nlawej-payment
    container_name: payment-service-1
    ports:
      - "6006:6005"
    environment:
      - NODE_ENV=development
      - SERVICE_NAME=payment-service
      - SERVICE_ID=payment-service-1
      - CONSUL_HOST=consul
      - HOST=payment-service-1
      - MONGO_URI=mongodb://root:example@mongodb:27017/Nlawej?authSource=admin
    depends_on:
      - consul
    restart: always
    networks:
      - nlawej-network

  payment-service-2:
    build: ./MicroServicesBackend/payment-service
    image: nlawej-payment
    container_name: payment-service-2
    ports:
      - "6007:6005"
    environment:
      - NODE_ENV=development
      - SERVICE_NAME=payment-service
      - SERVICE_ID=payment-service-2
      - CONSUL_HOST=consul
      - HOST=payment-service-2
      - MONGO_URI=mongodb://root:example@mongodb:27017/Nlawej?authSource=admin
    depends_on:
      - consul
    restart: always
    networks:
      - nlawej-network

  # Rating service instances
  rating-service:
    build: ./MicroServicesBackend/rating-service
    image: nlawej-rating
    container_name: rating-service
    ports:
      - "7000:7000"
    environment:
      - NODE_ENV=development
      - SERVICE_NAME=rating-service
      - SERVICE_ID=rating-service-0
      - CONSUL_HOST=consul
      - HOST=rating-service
      - MONGO_URI=mongodb://root:example@mongodb:27017/Nlawej?authSource=admin
    depends_on:
      - consul
    restart: always
    networks:
      - nlawej-network

  rating-service-1:
    build: ./MicroServicesBackend/rating-service
    image: nlawej-rating
    container_name: rating-service-1
    ports:
      - "7001:7000"
    environment:
      - NODE_ENV=development
      - SERVICE_NAME=rating-service
      - SERVICE_ID=rating-service-1
      - CONSUL_HOST=consul
      - HOST=rating-service-1
      - MONGO_URI=mongodb://root:example@mongodb:27017/Nlawej?authSource=admin
    depends_on:
      - consul
    restart: always
    networks:
      - nlawej-network

  rating-service-2:
    build: ./MicroServicesBackend/rating-service
    image: nlawej-rating
    container_name: rating-service-2
    ports:
      - "7002:7000"
    environment:
      - NODE_ENV=development
      - SERVICE_NAME=rating-service
      - SERVICE_ID=rating-service-2
      - CONSUL_HOST=consul
      - HOST=rating-service-2
      - MONGO_URI=mongodb://root:example@mongodb:27017/Nlawej?authSource=admin
    depends_on:
      - consul
    restart: always
    networks:
      - nlawej-network

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    networks:
      - nlawej-network
  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
    container_name: sonarqube
    networks:
    - nlawej-network
volumes:
  mongodb_data:
    driver: local
  jenkins_home:


networks:
  nlawej-network:
    driver: bridge